[gitlab]

# GitLab host
host = "https://gitlab.com"

# Information for securely interacting with GitLab. These are found/generated
# under https://gitlab.com/profile/personal_access_tokens
# A GitLab private token
access_token = ""

# Priority values above max_priority will be refused.
max_priority = 9001

[git]

# Use the local Git command.
# Because GitLab not support merge API, so the local_git is required.
local_git = true

# SSH private key. Needed only when the local Git command is used.
ssh_key = """
"""

# You must associate the commits with a public email address.
user = "Some Cool Project Bot"
email = "coolprojectbot-devel@example.com"

[web]

# The port homu listens on.
port = 54856

# Synchronize all open MRs on startup. "Synchronize" means fetch the state of
# all open MRs.
sync_on_start = true

# Set Sentry DSN to report exceptions to Sentry.
sentry_dns = ""

# Custom hooks can be added as well.
# Homu will ping the given endpoint with POSTdata of the form:
# {'body': 'comment body', 'extra_data': 'extra data', 'pull': pull req number}
# The extra data is the text specified in `@homu hookname=text`
#
# [hooks.hookname]
# trigger = "hookname" # will be triggered by @homu hookname or @homu hookname=text
# endpoint = "http://path/to/endpoint"
# access = "try" # access level required
# has_response = true # Should the response be posted back to github? Only allowed if realtime=true
# realtime = true # Should it only run in realtime mode? If false, this will be replayed each time homu is started (probably not what you want)

# An example configuration for repository (there can be many of these). NAME
# refers to your repo name.
[repo.NAME]

# Which repo are we talking about? You can get these fields from your repo URL:
#    gitlab.example.com/<owner>/<name>
owner = ""
name = ""

# Who can approve MRs (r+ rights)? You can put GitLab usernames here.
reviewers = []

# Who has 'try' rights? (try, retry, force, clean, prioritization). It's fine to
# keep this empty.
try_users = []

# Keep the commit history linear. Requires the local Git command.
#linear = false

# Auto-squash commits. Requires the local Git command.
#autosquash = true

# Maximum test duration allowed for testing a MR in this repository.
# Default to 10 hours.
#timeout = 36000

# Branch names. These settings are the defaults; it makes sense to leave these
# as-is.
#[repo.NAME.branch]
#
#auto = "auto"
#try = "try"
#rollup = "rollup"

[repo.NAME.gitlab]
# Arbitrary secret. You can generate one with: openssl rand -hex 20
secret = ""

# GitLab has no status push in Webhooks, so currently just support GitLab Pipeline Jobs.
# See also: https://docs.gitlab.com/ee/ci/pipelines.html#jobs
[repo.NAME.job.LABEL]
#
# String label set by jobs updates.
context = ""

# The database homu uses
[db]
# SQLite file
file = "main.db"
